--- # Deploy Jenkins  On AWS EC2  Instance 
-  hosts: aws
   remote_user: ec2-user
   become_method: sudo
   become: yes
   gather_facts: yes
   connection: ssh
   vars_files:
   - tomcat-vars.yml
   tasks:
   - name: Download Jenkins War
     get_url: url=http://mirrors.jenkins.io/war-stable/latest/jenkins.war dest=/opt/apache-tomcat-8.5.23/webapps/jenkins.war

   - name: ReStart Tomcat
     service: name=tomcat state=restarted enabled=yes

   - name: wait for tomcat to start
     wait_for: port={{http_port}}
