--- # All EC2 Remote Facts list module
- hosts: local
  connection: local
  become_method: sudo
  gather_facts: yes
  vars_files:
  - tomcat-vars.yml
  - awscreds.yml
  tasks:
  - name: Gathering remote facts of all ec2 instances
    ec2_remote_facts:
     region: '{{ aws_region }}'
     filters:
        vpc-id: vpc-7e0d761a
    register: ec2_facts
  #debug that output
  - name: Debug
    debug:
      msg: '{{ ec2_facts }}'
