--- # install docker,pull images and run
-  hosts: aws
   remote_user: ec2-user
   become_method: sudo
   become: true
   gather_facts: yes
   connection: ssh
   vars_files:
    - tomcat-vars.yml
   tasks:
    - name: Install python setuptools and docker
      yum:
        name: "{{ item }}"
        update_cache: yes
      with_items:
      - python-setuptools
      - docker
    - name: Install pypi
      easy_install:
        name: pip

    - name: Install docker-py to latest
      pip:
        name: "{{ item }}"
        state: latest
      with_items:
        - docker-py

    - name: start docker
      service:
        name: docker
        state: started

    - name: Pull tomcat jdk 8  image
      docker_image:
        name: navatharaagi/tomcatjdk8
        tag: latest

    - name: Start tomcat 8 container
      docker_container:
        name: tomcat8
        image: navatharaagi/tomcatjdk8
        state: started
        recreate: yes
        published_ports:
          - "8080:8080"
        exposed_ports:
          - 8080
