--- # install docker,pull images and run
-  hosts: aws
   remote_user: ec2-user
   become_method: sudo
   become: true
   gather_facts: yes
   connection: ssh
   vars_files:
    - tomcat-vars.yml
   tasks:
    - name: Install python setuptools and docker
      yum:
        name: "{{ item }}"
        update_cache: yes
      with_items:
      - python-setuptools
      - docker
    - name: Pull an image
      docker_image:
        name: navatharaagi/tomcatjdk8
        tag: latest



    
