--- # EC2 Remote Facts Running list module
- hosts: local
  connection: local
  gather_facts: yes
  vars_files:
  - awscreds.yml
  - tomcat-vars.yml
  tasks:
  - name: gathering remote ec2 facts of running intances
    ec2_remote_facts:
      region: '{{ aws_region }}'
      filters:
          instance-state-name: running
    register: ec2_facts
  # debug that output
  - name: Debug
    debug:
      msg: '{{ ec2_facts }}'
