--- # EC2 Facts Running Remotely facts listing module 
- hosts: local
  connection: local
  remote_user: class
  become_method: sudo
  gather_facts: yes
  vars_files:
  - awscreds.yml
  - tomcat-vars.yml
  - name: gathering remote ec2 facts of running intances
    ec2_remote_facts:
      region: '{{ aws_region }}'
      filters:
          instance-state-name: running
    register: ec2_facts
  - name: Debug
    debug:
     msg: '{{ ec2_facts }}'
