--- # EC2 Remote Facts Running list module
- hosts: local
  connection: local
  gather_facts: yes
  vars_files:
  - awscreds.yml
  tasks:
  - name: gathering remote ec2 facts of running intances
    ec2_remote_facts:
      region: '{{ aws_region }}'
      filters:
          instance-state-name: running
    register: ec2_facts
  # debug that output
  - name: Get only running instance IP addresses.
    debug:
      msg: "Instance: {{ ansible_ec2_instance_type }} has IP address: {{ item.1 }}"
    with_together:
      - "{{ ec2_facts.instances|selectattr('state', 'equalto', 'running')|map(attribute='tags.Name')|list }}"
      - "{{ ec2_facts.instances|selectattr('state', 'equalto', 'running')|map(attribute='private_ip_address')|list }}"
