--- # EC2  Remote Facts Running list module
- hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - awscreds.yml
  tasks:
  - name: Gather facts
    ec2_remote_facts:
     region: '{{ aws_region }}'
  #  just show  the instance-id
  - debug:
     msg: "{{ hostvars[inventory_hostname]['ansible_ec2_instance_id']}}"
  - name: destroy all instances
    ec2:
      state: 'absent'
      region: '{{ aws_region }}'
      instance_ids: '{{ item }}'
      wait: true
      with_items: hostvars[inventory_hostname]['ansible_ec2_instance_id']
