--- # EC2 Remote Facts Running list module
- hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - awscreds.yml
  tasks:
  - name: gathering remote ec2 facts of running intances
    ec2_remote_facts:
      region: '{{ aws_region }}'
      filters:
          instance-state-name: stopped
    register: ec2_facts

  - name: hostvars
    debug:
     var: hostvars[inventory_hostname]
  - name: ec2 id
    debug:
     msg: "{{ hostvars[inventory_hostname]['ec2_id'] }}"
  - name: Terminate instances
    ec2:
     state: absent
     instance_ids: '{{ ec2_id }}'
     region: '{{ aws_region }}'
     wait: True
        #vpc_subnet_id: subnet-29e63245
  # debug that output, which gives all ec2 detailed information
