--- # EC2 Remote Facts Running list module
- hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - awscreds.yml
  tasks:
  - name: Basic creation of t2.micro EC2 instance via ansible
    ec2:
      key_name: mykey
      instance_type: t2.micro
      image: ami-02eada62
      region: '{{ aws_region }}'
      group: MySecurityGroup
      count: 0
      instance_tags:
        Name: runningfact
      volumes:
       - device_name: /dev/xvda
         volume_size: 100
         delete_on_termination: yes
  # debug that output, which gives all ec2 detailed information
