--- # EC2 Remote Facts Running list module
- hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - awscreds.yml
  tasks:
  - name: Gather facts
    action: ec2_facts

  - name: Stop  instance
    local_action:
        module: ec2
        region: '{{ aws_region }}'
        instance_ids: "{{ansible_ec2_instance_id}}"
        state: stopped
