--- # EC2 Remote Facts Running list module
- hosts: local
  connection: local
  gather_facts: yes
  vars_files:
    - awscreds.yml
  tasks:
  - name: stop running ec2 instances
    ec2_remote_facts:
      region: '{{ aws_region }}'
    register: ec2_facts
  - name: Terminate instances
    ec2:
      state: 'absent'
      instance_ids: '{{ id }}'
      region: '{{ aws_region }}'
      wait: True
      vpc-id: vpc-7e0d761a
  - name: Debug
    debug:
        msg: '{{ ec2_facts }}'

        #vpc_subnet_id: subnet-29e63245
  # debug that output, which gives all ec2 detailed information
