--- # EC2 Remote Facts Running list module
- hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - awscreds.yml
  tasks:
  - name: Gathering remote facts of all ec2 instances
    ec2_remote_facts:
     region: '{{ aws_region }}'
     filters:
        vpc-id: vpc-7e0d761a
    register: ec2_facts
  #debug that output
  - name: Debug
    debug:
      msg: '{{ ec2_facts }}'
  - name: Get all instances ID and IP addresses.
    debug:
     msg: "Instance: {{ item.0 }} state: {{ item.1 }} "
    with_together:
     - "{{ ec2_facts.instances|map(attribute='id')|list }}"
     - "{{ ec2_facts.instances|map(attribute='state')|list }}"
     - "{{ ec2_facts.instances|selectattr('state', 'equalto', 'absent')|map(attribute='id')|list }}"

        #vpc_subnet_id: subnet-29e63245
  # debug that output, which gives all ec2 detailed information
