--- # EC2 Remote Facts Running list module
- hosts: local
  connection: local
  gather_facts: no
  vars_files:
    - awscreds.yml
  tasks:
  - name: Gather facts
    ec2_remote_facts:
     region: '{{ aws_region }}'


  - name: Stop  instance
    ec2:
        region: '{{ aws_region }}'
        instance_type: t2.micro
        instance_ids: '{{ ansible_ec2_instance_id }}'
        state: stopped
        wait: no
