--- # EC2 Remote Facts Running list module
- hosts: local
  connection: local
  gather_facts: yes
  vars_files:
    - awscreds.yml
  tasks:
  - name: stop running ec2 instances
    ec2:
        region: '{{ aws_region }}'
        state: absent
        vpc-id: vpc-7e0d761a
        instance_ids: '{{ id }}'
        #vpc_subnet_id: subnet-29e63245
  # debug that output, which gives all ec2 detailed information
