--- # AWS EC2 Instance Communication Shell Command Example
-  hosts: ec2-13-56-189-69.us-west-1.compute.amazonaws.com
   remote_user: ec2-user
   become_method: sudo
   gather_facts: yes
   connection: ssh
   tasks:
   - name: Execute a shell command for listing the directory
     shell: ls -al ~
     register: result
   - name: display the results in JSON format
     debug: var=result
