--- #AWS S3 MODULE EXAMPLE
- hosts : localhost
  connection: local
  remote_user: test
  become_method: sudo
  gather_facts: no      #since we are running on our own server “test"
  vars_files:
  - files/awscreds.yml
  tasks:
  - name:  Create an S3 bucket
    s3:
      aws_access_key:  “{{ aws_id }}”
      aws_secret_key:  “{{ aws_key }}”
      region:  “{{ aws_region }}”
      bucket: ansiblebucket2
      mode: create
      permission: public-read-write
    register: create_bucket
  - name: Copy the files to the bucket
    s3:
      aws_access_key:  “{{ aws_id }}”
      aws_secret_key:  “{{ aws_key }}”
      region:  “{{ aws_region }}”
      bucket: ansiblebucket2
      object:  /Playbooks/aws_iam.yml  #give file which we want to copy
      src:  /home/test/Playbooks/aws_iam.yml
      mode: put
    register:  copy_files
  - name:  Output of creation
    debug:  var=create_bucket
  - name:  Output of copy
    debug:  var=copy_files
# S3 console,”ansiblebucket2”bucket,”Playbooks" folder, “aws_iam.yml” file will be created.
