--- #AWS IAM MODULE EXAMPLE
- hosts : localhost
  connection: local
  remote_user: test
  become_method: sudo
  gather_facts: no            /*since we are running on our own server “test"
  vars_files:
  - files/awscreds.yml
  tasks:
  - name:  Create a couple of IAM Users
    iam:
      aws_access_key:  “{{ aws_id }}”
      aws_secret_key:  “{{ aws_key }}”
      region:  “{{ aws_region }}”
      iam_type:  user     #to create a user or group by giving type
      name:  “{{  item  }}”       #item keyword variable
      state:  present
      password:  “password”
      access_key_state:  create     /*to create access key
      with_items:
      -  tmp1       #user tmp1
      -  tmp2       #user tmp2
