--- # Gather EC2 facts from my remote instances
- hosts: aws
  remote_user: ec2-user
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
    - name: Gather EC2 facts about runing instances
      action: ec2_facts
    - name: Display the instance type
      debug: msg='{{ ansible_ec2_instance_type }}'
