--- # EC2 TAG MODULE EXAMPLE
- hosts: localhost
  connection: local
  remote_user: test
  become_method: sudo
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Label an existing volume so we know what it is
    ec2_vol:
      aws_access_key: “{{ aws_id }}”
      aws_secret_key: “{{ aws_key }}”
      region: '{{aws_region }}'
      instance: copy & paste instance id from EC2
      state: list
    register: volume_result
  - debug: msg={{ volume_result }}
