--- # EC2_REMOTE FACTS MODULE EXAMPLE
- hosts:  local
  connection: local
  remote_user: test
  become_method: sudo
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Take a snapshot of the running instance root volume
    ec2_snapshot:
      aws_access_key: “{{ aws_id }}”
      aws_secret_key: “{{ aws_key }}”
      region: '{{ aws_region }}'
      snapshot_id: paste the copied snapshot Id
      state: absent
      wait: no
    register: snapshot
