--- # EC2  MODULE  PROVISIONING EXAMPLE
- hosts:  local
  connection: local
  remote_user: test
  become_method: sudo
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Basic Provisioning of two t2.micro EC2 instances
    ec2:
      region: '{{ aws_region }}'
      image: ami-3a674d5a
      instance_type: t2.micro
      count: 2
