--- # EC2 TAG MODULE EXAMPLE
- hosts: localhost
  connection: local
  remote_user: test
  become_method: sudo
  gather_facts: no
  tasks:
  - name: Label an existing volume so we know what it is
    ec2_tags:
      state: present
      tags:
        Name: data_volume
    register: voltags
