--- #VPC_NET MODULE EXAMPLE
- hosts : localhost
  connection: local
  remote_user: test
  become_method: sudo
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name:  Create a New VPC called MyNewVPC
    ec2_vpc_net:
      aws_access_key:  “{{ aws_id }}”
      aws_secret_key:  “{{ aws_key }}”
      region:  “{{aws_region }}”
      name: MyNewVPC
      state: present
      cidr_block:  172.17.1.0/24
    register:  vpcnetblock
  - name: Print the resulting JSON output
    debug:  msg=vpcnetblock  # MyNewVPC will be created with given ip
