--- # EC2 TAG MODULE EXAMPLE
- hosts: localhost
  connection: local
  remote_user: test
  become_method: sudo
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Find our AMI ID
    ec2_ami_find:
      region: '{{ aws_region }}'
      owner: self
