--- # AWS EC2 Instance Communication Shell Command Example
-  hosts: aws
   remote_user: ec2-user
   become_method: sudo
   become: yes
   gather_facts: yes
   connection: ssh
   vars_files:
   - tomcat-vars.yml
   tasks:
   - name: Download Jenkins War
     get_url: url=http://mirrors.jenkins.io/war-stable/latest/jenkins.war dest=/usr/share/tomcat/webapps

   - name: Start Tomcat
     service: name=tomcat state=started enabled=yes
     
   - name: wait for tomcat to start
     wait_for: port={{http_port}}
